
05.Jul 2020 17:15:49 predict module error
./2_RAW_DATA_DIR/sample_submission.csv not found.
Traceback (most recent call last):
  File ".\_3_predict.py", line 116, in predict
    submission_template = np.genfromtxt(''.join([local_script_settings['raw_data_path'], 'sample_submission.csv']),
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ./2_RAW_DATA_DIR/sample_submission.csv not found.

05.Jul 2020 17:17:49 predict module error
./2_RAW_DATA_DIR/sample_submission.csv not found.
Traceback (most recent call last):
  File ".\_3_predict.py", line 116, in predict
    submission_template = np.genfromtxt(''.join([local_script_settings['raw_data_path'], 'sample_submission.csv']),
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ./2_RAW_DATA_DIR/sample_submission.csv not found.

05.Jul 2020 17:18:41 predict module error
./2_RAW_DATA_DIR/sample_submission.csv not found.
Traceback (most recent call last):
  File ".\_3_predict.py", line 116, in predict
    submission_template = np.genfromtxt(''.join([local_script_settings['raw_data_path'], 'sample_submission.csv']),
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ./2_RAW_DATA_DIR/sample_submission.csv not found.

05.Jul 2020 17:25:38 predict module error
./2_RAW_DATA_DIR/sample_submission.csv not found.
Traceback (most recent call last):
  File ".\_3_predict.py", line 116, in predict
    submission_template = np.genfromtxt(''.join([local_script_settings['raw_data_path'], 'sample_submission.csv']),
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ./2_RAW_DATA_DIR/sample_submission.csv not found.

05.Jul 2020 17:27:06 predict module error
./2_RAW_DATA_DIR/sample_submission.csv not found.
Traceback (most recent call last):
  File ".\_3_predict.py", line 116, in predict
    submission_template = np.genfromtxt(''.join([local_script_settings['raw_data_path'], 'sample_submission.csv']),
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ./2_RAW_DATA_DIR/sample_submission.csv not found.

05.Jul 2020 17:27:44 predict module error
./2_RAW_DATA_DIR/sample_submission.csv not found.
Traceback (most recent call last):
  File ".\_3_predict.py", line 116, in predict
    submission_template = np.genfromtxt(''.join([local_script_settings['raw_data_path'], 'sample_submission.csv']),
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\carpeta_p_pycharm\M5_kaggle_accuracy\venv\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ./2_RAW_DATA_DIR/sample_submission.csv not found.

05.Jul 2020 17:29:10 correct prediction process

05.Jul 2020 18:16:34 correct prediction process

05.Jul 2020 18:16:51 correct prediction process

05.Jul 2020 18:17:15 correct prediction process

05.Jul 2020 18:18:04 correct prediction process

05.Jul 2020 18:18:39 correct prediction process

07.Jul 2020 10:48:52 correct prediction process

07.Jul 2020 10:54:33 correct prediction process

07.Jul 2020 10:59:54 correct prediction process

07.Jul 2020 11:02:32 correct prediction process

07.Jul 2020 11:04:17 correct prediction process

07.Jul 2020 11:06:18 correct prediction process

07.Jul 2020 11:07:44 correct prediction process

07.Jul 2020 11:11:52 correct prediction process

07.Jul 2020 13:56:31 correct prediction process

07.Jul 2020 20:02:37 correct prediction process

07.Jul 2020 20:04:43 correct prediction process

07.Jul 2020 20:05:33 correct prediction process

07.Jul 2020 20:09:47 correct prediction process

07.Jul 2020 20:24:53 correct prediction process
